"""empty message

Revision ID: 04f5959b727c
Revises: 8b20488f714c
Create Date: 2022-01-27 22:27:01.950552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f5959b727c'
down_revision = '8b20488f714c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth_tokens', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_auth_tokens_request_id_fkey', 'user_auth_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'user_auth_tokens', 'user', ['user_id'], ['id'])
    op.drop_column('user_auth_tokens', 'request_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth_tokens', sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_auth_tokens', type_='foreignkey')
    op.create_foreign_key('user_auth_tokens_request_id_fkey', 'user_auth_tokens', 'user', ['request_id'], ['id'])
    op.drop_column('user_auth_tokens', 'user_id')
    # ### end Alembic commands ###
