"""empty message

Revision ID: 0598e2fe76e2
Revises: 9bb466a6ddbf
Create Date: 2022-01-27 23:20:48.607290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0598e2fe76e2'
down_revision = '9bb466a6ddbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=512), nullable=True))
    op.drop_column('user_auth_tokens', 'access_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth_tokens', sa.Column('access_token', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
