"""empty message

Revision ID: 09b09562c7fc
Revises: d34c8c0a74b1
Create Date: 2022-05-10 20:27:40.801882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b09562c7fc'
down_revision = 'd34c8c0a74b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('good_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['good_id'], ['good.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('category_file')
    op.add_column('category', sa.Column('file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'file', ['file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'file_id')
    op.create_table('category_file',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='category_file_category_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], name='category_file_file_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='category_file_pkey')
    )
    op.drop_table('good_file')
    # ### end Alembic commands ###
