"""empty message

Revision ID: 10040e44dc34
Revises: b82ae2338144
Create Date: 2022-01-30 01:31:23.318300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10040e44dc34'
down_revision = 'b82ae2338144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('management3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('management3',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='management3_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='management3_pkey')
    )
    # ### end Alembic commands ###
