"""empty message

Revision ID: 106a3356f025
Revises: 5cb6b761af46
Create Date: 2022-01-29 22:58:01.097857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106a3356f025'
down_revision = '5cb6b761af46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_attempts', sa.Integer(), nullable=True))
    op.drop_column('user', 'attempts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'login_attempts')
    # ### end Alembic commands ###
