"""empty message

Revision ID: 16a19b6da42b
Revises: b90848aa4008
Create Date: 2022-04-30 18:30:27.149397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16a19b6da42b'
down_revision = 'b90848aa4008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_course', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('teacher_course', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_course', sa.Column('name', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('teacher_course', 'description')
    # ### end Alembic commands ###
