"""empty message

Revision ID: 1b1e01887179
Revises: 1dc3b5e7fe2c
Create Date: 2022-01-30 01:44:20.329967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1e01887179'
down_revision = '1dc3b5e7fe2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name2', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
