"""empty message

Revision ID: 1dc3b5e7fe2c
Revises: 3a2396c190e2
Create Date: 2022-01-30 01:43:47.117873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1dc3b5e7fe2c'
down_revision = '3a2396c190e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests2')
    op.add_column('user_auth_tokens', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user_auth_tokens', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_auth_tokens', 'updated_at')
    op.drop_column('user_auth_tokens', 'created_at')
    op.create_table('tests2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tests2_pkey')
    )
    # ### end Alembic commands ###
