"""empty message

Revision ID: 200924dbc7ca
Revises: f4c7e80113ad
Create Date: 2022-01-30 01:25:24.295015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200924dbc7ca'
down_revision = 'f4c7e80113ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name2', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name2')
    # ### end Alembic commands ###
