"""empty message

Revision ID: 22ca4cdc7bb5
Revises: 29d2a79b0cb2
Create Date: 2022-01-30 01:33:51.623061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ca4cdc7bb5'
down_revision = '29d2a79b0cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_auth_tokens4',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('access_token', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_auth_tokens', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user_auth_tokens', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_auth_tokens', 'updated_at')
    op.drop_column('user_auth_tokens', 'created_at')
    op.drop_table('user_auth_tokens4')
    # ### end Alembic commands ###
