"""empty message

Revision ID: 284e40bbb484
Revises: 59f65fa6804b
Create Date: 2022-01-27 22:21:58.648507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284e40bbb484'
down_revision = '59f65fa6804b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth_tokens', sa.Column('token', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_auth_tokens', 'token')
    # ### end Alembic commands ###
