"""empty message

Revision ID: 28cae77ea7ad
Revises: 3e67ea14ca99
Create Date: 2022-04-27 18:03:55.721338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cae77ea7ad'
down_revision = '3e67ea14ca99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('teacher', sa.Column('details_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teacher', 'teacher_details', ['details_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'details_id')
    op.drop_table('teacher_details')
    # ### end Alembic commands ###
