"""empty message

Revision ID: 2dc068ed9a17
Revises: b7747b1d941d
Create Date: 2022-04-30 17:16:40.775161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2dc068ed9a17'
down_revision = 'b7747b1d941d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_course', 'dates')
    op.drop_column('teacher_details', 'dates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_details', sa.Column('dates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('teacher_course', sa.Column('dates', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
