"""empty message

Revision ID: 2e5fb4ccecd4
Revises: 71cac9ea37bf
Create Date: 2022-03-14 21:27:39.794203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5fb4ccecd4'
down_revision = '71cac9ea37bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('role', 'alias2')
    op.alter_column('role_permissions', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('role_permissions', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_permissions', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('role_permissions', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('role', sa.Column('alias2', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_table('user_role')
    # ### end Alembic commands ###
