"""empty message

Revision ID: 31cb920cc4a4
Revises: 1b1e01887179
Create Date: 2022-01-30 03:20:20.544844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31cb920cc4a4'
down_revision = '1b1e01887179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_password_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reset_password_at')
    # ### end Alembic commands ###
