"""empty message

Revision ID: 3ad4ce7b6c56
Revises: 72a861e5e899
Create Date: 2022-05-01 16:09:33.900432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad4ce7b6c56'
down_revision = '72a861e5e899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_read_notification', 'user_id')
    op.drop_column('user_read_notification', 'notification_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_read_notification', sa.Column('notification_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('user_read_notification', sa.Column('user_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
