"""empty message

Revision ID: 3e67ea14ca99
Revises: ef9a2e91b499
Create Date: 2022-04-27 17:51:41.766717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e67ea14ca99'
down_revision = 'ef9a2e91b499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('work_experience', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'work_experience')
    # ### end Alembic commands ###
