"""empty message

Revision ID: 44265f420b4b
Revises: ea97e5aaa936
Create Date: 2022-03-19 17:25:27.983702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44265f420b4b'
down_revision = 'ea97e5aaa936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('file_id', sa.Integer(), nullable=True))
    op.drop_constraint('category_image_fkey', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'file', ['file_id'], ['id'], ondelete='CASCADE')
    op.drop_column('category', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('image', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key('category_image_fkey', 'category', 'file', ['image'], ['id'], ondelete='CASCADE')
    op.drop_column('category', 'file_id')
    # ### end Alembic commands ###
