"""empty message

Revision ID: 4651b08ea212
Revises: 44265f420b4b
Create Date: 2022-03-19 18:19:58.548973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4651b08ea212'
down_revision = '44265f420b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('good', sa.Column('file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'good', 'file', ['file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'good', type_='foreignkey')
    op.drop_column('good', 'file_id')
    # ### end Alembic commands ###
