"""empty message

Revision ID: 47fd42b921ad
Revises: 28cae77ea7ad
Create Date: 2022-04-27 18:07:56.578763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fd42b921ad'
down_revision = '28cae77ea7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teacher_details_id_fkey', 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'details_id')
    op.add_column('teacher_details', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teacher_details', 'teacher', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_details', type_='foreignkey')
    op.drop_column('teacher_details', 'teacher_id')
    op.add_column('teacher', sa.Column('details_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('teacher_details_id_fkey', 'teacher', 'teacher_details', ['details_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
