"""empty message

Revision ID: 529028360a82
Revises: 4c779f1a4d71
Create Date: 2022-01-28 19:32:18.012582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529028360a82'
down_revision = '4c779f1a4d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_auth_tokens_user_id_fkey', 'user_auth_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'user_auth_tokens', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_auth_tokens', type_='foreignkey')
    op.create_foreign_key('user_auth_tokens_user_id_fkey', 'user_auth_tokens', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
