"""empty message

Revision ID: 56af2643ea44
Revises: 22ca4cdc7bb5
Create Date: 2022-01-30 01:40:41.412858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56af2643ea44'
down_revision = '22ca4cdc7bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('access_token', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_auth_tokens4')
    op.drop_column('user_auth_tokens', 'updated_at')
    op.drop_column('user_auth_tokens', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth_tokens', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_auth_tokens', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table('user_auth_tokens4',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_auth_tokens4_pkey')
    )
    op.drop_table('base')
    # ### end Alembic commands ###
