"""empty message

Revision ID: 58f421f5924c
Revises: 09b09562c7fc
Create Date: 2022-06-04 13:55:03.234921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f421f5924c'
down_revision = '09b09562c7fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('nota')
    op.drop_index('curs_id_uindex', table_name='curs')
    op.drop_table('curs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curs',
    sa.Column('titlu', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('an', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('semestrul', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('credite', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='curs_pk')
    )
    op.create_index('curs_id_uindex', 'curs', ['id'], unique=False)
    op.create_table('nota',
    sa.Column('nr_matricol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id_curs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valoare', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('data_notare', sa.DATE(), autoincrement=False, nullable=True)
    )
    op.create_table('student',
    sa.Column('nr_matricol', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('nume', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('an', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('grupa', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bursa', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_nastere', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('prenume', sa.VARCHAR(length=15), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
