"""empty message

Revision ID: 59f65fa6804b
Revises: 56537c6b374f
Create Date: 2022-01-27 22:19:58.008088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f65fa6804b'
down_revision = '56537c6b374f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_auth_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_auth_tokens')
    # ### end Alembic commands ###
