"""empty message

Revision ID: 5cb6b761af46
Revises: d62a569b2cba
Create Date: 2022-01-29 22:57:50.660836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb6b761af46'
down_revision = 'd62a569b2cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'attempts')
    # ### end Alembic commands ###
