"""empty message

Revision ID: 62be1d0885eb
Revises: 598f13df5c5c
Create Date: 2021-04-15 02:26:21.961390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62be1d0885eb'
down_revision = '598f13df5c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
