"""empty message

Revision ID: 71cac9ea37bf
Revises: f9fec8f17c34
Create Date: 2022-03-13 23:42:50.214126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71cac9ea37bf'
down_revision = 'f9fec8f17c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('alias2', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'alias2')
    # ### end Alembic commands ###
