"""empty message

Revision ID: 724be92e6475
Revises: c70e32c8cec6
Create Date: 2021-04-15 02:44:18.917072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724be92e6475'
down_revision = 'c70e32c8cec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
