"""empty message

Revision ID: 734314ad5b82
Revises: 98f6e363b58a
Create Date: 2022-03-13 20:18:32.837138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734314ad5b82'
down_revision = '98f6e363b58a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permission', 'alias',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.create_unique_constraint(None, 'permission', ['alias'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permission', type_='unique')
    op.alter_column('permission', 'alias',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
