"""empty message

Revision ID: 78ee40072427
Revises: 65ecebf73ba6
Create Date: 2022-03-02 08:56:19.216200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ee40072427'
down_revision = '65ecebf73ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_position', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.drop_constraint('teacher_position_user_id_fkey', 'teacher_position', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_position', 'teacher', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.drop_column('teacher_position', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_position', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'teacher_position', type_='foreignkey')
    op.create_foreign_key('teacher_position_user_id_fkey', 'teacher_position', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('teacher_position', 'teacher_id')
    # ### end Alembic commands ###
