"""empty message

Revision ID: 8f3ecbc4e77d
Revises: 47fd42b921ad
Create Date: 2022-04-30 16:26:33.564247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3ecbc4e77d'
down_revision = '47fd42b921ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('teacher_position_id_fkey', 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'position_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('teacher_position_id_fkey', 'teacher', 'position', ['position_id'], ['id'], ondelete='CASCADE')
    op.drop_table('teacher_positions')
    # ### end Alembic commands ###
