"""empty message

Revision ID: 9bb466a6ddbf
Revises: b3c855ddc341
Create Date: 2022-01-27 23:11:51.406951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb466a6ddbf'
down_revision = 'b3c855ddc341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth_tokens', sa.Column('access_token', sa.String(length=512), nullable=True))
    op.alter_column('user_auth_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_auth_tokens', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth_tokens', sa.Column('token', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.alter_column('user_auth_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user_auth_tokens', 'access_token')
    # ### end Alembic commands ###
