"""empty message

Revision ID: a2b72a114ce5
Revises: 9a166cef3ead
Create Date: 2022-05-05 09:44:10.972873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2b72a114ce5'
down_revision = '9a166cef3ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission')
    op.add_column('user', sa.Column('is_super_user', sa.Boolean(), server_default='False', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_super_user')
    op.create_table('permission',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('alias', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='permission_pkey'),
    sa.UniqueConstraint('alias', name='permission_alias_key'),
    sa.UniqueConstraint('endpoint', name='permission_endpoint_key'),
    sa.UniqueConstraint('method', name='permission_method_key')
    )
    # ### end Alembic commands ###
