"""empty message

Revision ID: aa4aaf44b049
Revises: 6c937a7bc8a0
Create Date: 2022-04-26 23:21:12.918773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4aaf44b049'
down_revision = '6c937a7bc8a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teacher', 'position', ['position_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'position_id')
    # ### end Alembic commands ###
