"""empty message

Revision ID: b7747b1d941d
Revises: c33a0b72943a
Create Date: 2022-04-30 17:15:14.703059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7747b1d941d'
down_revision = 'c33a0b72943a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_details', sa.Column('dates', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('teacher_details', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_details', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('teacher_details', 'dates')
    # ### end Alembic commands ###
