"""empty message

Revision ID: b8e52adf732b
Revises: 8f3ecbc4e77d
Create Date: 2022-04-30 16:31:36.943921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8e52adf732b'
down_revision = '8f3ecbc4e77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teacher_degree_id_fkey', 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'degree_id')
    op.drop_column('teacher', 'work_experience')
    op.add_column('teacher_positions', sa.Column('degree_id', sa.Integer(), nullable=True))
    op.add_column('teacher_positions', sa.Column('work_experience', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'teacher_positions', 'degree', ['degree_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_positions', type_='foreignkey')
    op.drop_column('teacher_positions', 'work_experience')
    op.drop_column('teacher_positions', 'degree_id')
    op.add_column('teacher', sa.Column('work_experience', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('teacher', sa.Column('degree_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('teacher_degree_id_fkey', 'teacher', 'degree', ['degree_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
