"""empty message

Revision ID: c3c252c9918f
Revises: b8e52adf732b
Create Date: 2022-04-30 17:01:34.255900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c252c9918f'
down_revision = 'b8e52adf732b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('phone', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'phone')
    # ### end Alembic commands ###
