"""empty message

Revision ID: cfe217343c25
Revises: 04f5959b727c
Create Date: 2022-01-27 22:36:17.608823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe217343c25'
down_revision = '04f5959b727c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_auth_tokens', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth_tokens', sa.Column('token', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
