"""empty message

Revision ID: d020c3cef2fa
Revises: aa4aaf44b049
Create Date: 2022-04-26 23:22:20.664736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd020c3cef2fa'
down_revision = 'aa4aaf44b049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('degree_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teacher', 'degree', ['degree_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'degree_id')
    # ### end Alembic commands ###
