"""empty message

Revision ID: d0c6da117b38
Revises: 2dc068ed9a17
Create Date: 2022-04-30 17:16:47.485047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0c6da117b38'
down_revision = '2dc068ed9a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_course', sa.Column('dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('teacher_details', sa.Column('dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_details', 'dates')
    op.drop_column('teacher_course', 'dates')
    # ### end Alembic commands ###
