"""empty message

Revision ID: d62a569b2cba
Revises: 7de133150c5f
Create Date: 2022-01-28 21:01:25.704612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd62a569b2cba'
down_revision = '7de133150c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), server_default='False', nullable=True))
    op.drop_column('user', 'reset_code_expire')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_code_expire', postgresql.TIMESTAMP(), server_default=sa.text("'2022-01-27 01:39:24.56128'::timestamp without time zone"), autoincrement=False, nullable=True))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
