"""empty message

Revision ID: df358c479881
Revises: e4e6bd5c1d00
Create Date: 2022-03-19 19:46:51.605731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df358c479881'
down_revision = 'e4e6bd5c1d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('good', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('good', sa.Column('width', sa.Float(), nullable=True))
    op.add_column('good', sa.Column('length', sa.Float(), nullable=True))
    op.add_column('good', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('good', 'price')
    op.drop_column('good', 'length')
    op.drop_column('good', 'width')
    op.drop_column('good', 'height')
    # ### end Alembic commands ###
