"""empty message

Revision ID: e0b31fde869a
Revises: 
Create Date: 2022-01-26 20:05:54.822930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b31fde869a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('guard', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('old_token', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=12), server_default='user', nullable=True),
    sa.Column('platform', sa.String(), server_default='', nullable=True),
    sa.Column('browser', sa.String(), server_default='', nullable=True),
    sa.Column('reset_code', sa.String(), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('client')
    # ### end Alembic commands ###
