"""empty message

Revision ID: e5d273e385c7
Revises: 3ad4ce7b6c56
Create Date: 2022-05-01 16:10:29.212817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d273e385c7'
down_revision = '3ad4ce7b6c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_read_notification', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('user_read_notification', sa.Column('notification_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_read_notification', 'notification', ['notification_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_read_notification', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_read_notification', type_='foreignkey')
    op.drop_constraint(None, 'user_read_notification', type_='foreignkey')
    op.drop_column('user_read_notification', 'notification_id')
    op.drop_column('user_read_notification', 'user_id')
    # ### end Alembic commands ###
