"""empty message

Revision ID: eb8f56139854
Revises: 16a19b6da42b
Create Date: 2022-04-30 18:30:39.534392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8f56139854'
down_revision = '16a19b6da42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_course', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_course', 'name')
    # ### end Alembic commands ###
