"""empty message

Revision ID: f4c7e80113ad
Revises: 106a3356f025
Create Date: 2022-01-29 23:31:29.742987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c7e80113ad'
down_revision = '106a3356f025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_blocked_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login_blocked_time')
    # ### end Alembic commands ###
