"""empty message

Revision ID: fa605e9a477d
Revises: 0598e2fe76e2
Create Date: 2022-01-27 23:24:13.740904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa605e9a477d'
down_revision = '0598e2fe76e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token')
    op.add_column('user_auth_tokens', sa.Column('access_token', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_auth_tokens', 'access_token')
    op.add_column('user', sa.Column('token', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
