import src.modules.auth.controller
import src.modules.users.controller
import src.modules.permissions.controller
import src.modules.roles.controller
import src.modules.categories
import src.modules.goods
import src.modules.teacher
import src.modules.course
import src.modules.degrees
import src.modules.positions
import src.modules.profile
import src.modules.notifications
